### ISSUE TITLE
OAI Schnittstelle Packages läuft nicht richtig

### ISSUE THREAD

**Issue by Moetez16** [hbz/gokb-phase1#10]
Wenn man diese Seite phaeton.hbz-nrw.de/gokb/oai/packages?verb=ListRecords&metadataPrefix=gokb aufruft, dauert es Ewigkeiten bis irgendwas angezeigt wird. 

Läuft das Lokal bei dir Moritz ohne Probleme, auch dann wenn viele Packages drin sind?

Danke.

**Comment by hornmo** [comment]
Hallo Moe,

bei mir lokal gibt es keine Probleme. Ich habe zur Zeit 122 Pakete drin. 

Kann aber sein, dass es hauptsächlich darauf ankommt, wieviele TIPPs die Pakete auf der ersten Seite haben. Hast du irgendwas in den Logs gefunden?

**Comment by Moetez16** [comment]
Hallo Moritz,

wenn ich die URL im Firefox öffne, dann stürzt dieser immer ab. Wenn ich die URL im Chrome öffne, dann erzeugt er eine Ausgabe aber diese ist nicht XML. 

Hier ist das Screeanshot.

![2017-05-24_gokb_oai_packages](https://cloud.githubusercontent.com/assets/20820400/26389593/01af607e-405b-11e7-98c8-ae97c55016cd.png)

**Comment by hornmo** [comment]
Bin mir ziemlich sicher, dass das mit der Anzahl der TIPPs in den Paketen und den Browsern zu tun hat. In der OAI-Antwort werden mindestens 3 Pakete mit ihren TIPPs angezeigt. Wenn eine Antwort zum Beispiel 3 sehr große Pakete hat, dann wird das eine Menge XML. Generell sollte hier aber die Ansicht im Browser auch egal sein... das ist ja eh nicht der Zweck. Bei der Anzeige im Browser kommt in der Regel eine Menge an Overhead dazu (Ich hatte schon Antworten, die bei der Verarbeitung keine Probleme bereitet haben, aber im Browser letztendlich mehrere GB RAM - vor dem Crash - verbraucht haben). Alle (?) Browser haben Probleme mit der Anzeige von größeren XML-Dateien. Für Firefox gibt es [hier](https://superuser.com/questions/282146/how-can-i-get-firefox-to-open-xml-files-in-notepad-instead-of-in-the-browser) eine Lösung, um alles gleich in einem externen Tool zu öffnen.

TL:DR: Solange es keine Probleme bei der Verarbeitung mit geeigneten Parsern gibt, würde ich die Anzeige im Browser nicht als Problem sehen. Meine Pakete mit ~1500 TIPPs kommen auf jeden Fall in LAS:eR an.

**Comment by Moetez16** [comment]
Ja der Browser ist egal. Aber es geht darum das die Paket in LAS:eR ankommen. Die kommen aber nicht an. Das ist das hauptsächliche Problem.

**Comment by hornmo** [comment]
Ah, ja das ist ein Problem. Kommen gar keine an, oder fehlen da welche? Kannst du mir sonst die größten Pakete mal schicken?

**Comment by Moetez16** [comment]
Wenn ich den Global Data Sync starte. Passiert nichts danach. 

In den Logs ist nur das zu sehen: 

Get latest changes
Attempt get...
com.k_int.goai.OaiClient::getChangesSince - Make http request..
2017-06-06 10:20:00,001 [quartzScheduler_Worker-8] DEBUG batch.IndexUpdateJob  - ****Running Index Update Job****
2017-06-06 10:20:00,002 [quartzScheduler_Worker-8] DEBUG kbplus.DataloadService  - Exiting FT update - one already running
2017-06-06 10:20:00,002 [quartzScheduler_Worker-8] DEBUG kbplus.DataloadService  - doFTUpdate
2017-06-06 10:20:00,002 [quartzScheduler_Worker-8] DEBUG kbplus.DataloadService  - Execute IndexUpdateJob starting at Tue Jun 06 10:20:00 CEST 2017
2017-06-06 10:20:00,003 [quartzScheduler_Worker-8] DEBUG kbplus.DataloadService  - Updating ES site mapping...
2017-06-06 10:20:00,004 [quartzScheduler_Worker-7] DEBUG batch.HeartbeatJob  - Heartbeat Job
2017-06-06 10:20:00,072 [quartzScheduler_Worker-8] DEBUG kbplus.DataloadService  - updateES - com.k_int.kbplus.Org
2017-06-06 10:20:00,074 [quartzScheduler_Worker-8] DEBUG kbplus.DataloadService  - result of findByDomain: com.k_int.kbplus.FTControl : 7
2017-06-06 10:20:00,074 [quartzScheduler_Worker-8] DEBUG kbplus.DataloadService  - updateES com.k_int.kbplus.Org since 1496407183000
2017-06-06 10:20:00,077 [quartzScheduler_Worker-8] DEBUG kbplus.DataloadService  - Query completed.. processing rows...
2017-06-06 10:20:00,077 [quartzScheduler_Worker-8] DEBUG kbplus.DataloadService  - Processed 0 records for com.k_int.kbplus.Org
2017-06-06 10:20:00,077 [quartzScheduler_Worker-8] DEBUG kbplus.DataloadService  - Completed processing on com.k_int.kbplus.Org - saved 0 records
2017-06-06 10:20:00,077 [quartzScheduler_Worker-8] DEBUG kbplus.DataloadService  - updateES - com.k_int.kbplus.TitleInstance
2017-06-06 10:20:00,078 [quartzScheduler_Worker-8] DEBUG kbplus.DataloadService  - result of findByDomain: com.k_int.kbplus.FTControl : 8
2017-06-06 10:20:00,078 [quartzScheduler_Worker-8] DEBUG kbplus.DataloadService  - updateES com.k_int.kbplus.TitleInstance since 1495344145000
2017-06-06 10:20:00,216 [quartzScheduler_Worker-8] DEBUG kbplus.DataloadService  - Query completed.. processing rows...
2017-06-06 10:20:00,216 [quartzScheduler_Worker-8] DEBUG kbplus.DataloadService  - Processed 0 records for com.k_int.kbplus.TitleInstance
2017-06-06 10:20:00,216 [quartzScheduler_Worker-8] DEBUG kbplus.DataloadService  - Completed processing on com.k_int.kbplus.TitleInstance - saved 0 records
2017-06-06 10:20:00,216 [quartzScheduler_Worker-8] DEBUG kbplus.DataloadService  - updateES - com.k_int.kbplus.Package
2017-06-06 10:20:00,218 [quartzScheduler_Worker-8] DEBUG kbplus.DataloadService  - result of findByDomain: com.k_int.kbplus.FTControl : 9
2017-06-06 10:20:00,218 [quartzScheduler_Worker-8] DEBUG kbplus.DataloadService  - updateES com.k_int.kbplus.Package since 0
2017-06-06 10:20:00,220 [quartzScheduler_Worker-8] DEBUG kbplus.DataloadService  - Query completed.. processing rows...
2017-06-06 10:20:00,220 [quartzScheduler_Worker-8] DEBUG kbplus.DataloadService  - Processed 0 records for com.k_int.kbplus.Package
2017-06-06 10:20:00,220 [quartzScheduler_Worker-8] DEBUG kbplus.DataloadService  - Completed processing on com.k_int.kbplus.Package - saved 0 records
2017-06-06 10:20:00,220 [quartzScheduler_Worker-8] DEBUG kbplus.DataloadService  - updateES - com.k_int.kbplus.License
2017-06-06 10:20:00,221 [quartzScheduler_Worker-8] DEBUG kbplus.DataloadService  - result of findByDomain: com.k_int.kbplus.FTControl : 10
2017-06-06 10:20:00,221 [quartzScheduler_Worker-8] DEBUG kbplus.DataloadService  - updateES com.k_int.kbplus.License since 1496409155000
2017-06-06 10:20:00,222 [quartzScheduler_Worker-8] DEBUG kbplus.DataloadService  - Query completed.. processing rows...
2017-06-06 10:20:00,222 [quartzScheduler_Worker-8] DEBUG kbplus.DataloadService  - Processed 0 records for com.k_int.kbplus.License
2017-06-06 10:20:00,222 [quartzScheduler_Worker-8] DEBUG kbplus.DataloadService  - Completed processing on com.k_int.kbplus.License - saved 0 records
2017-06-06 10:20:00,222 [quartzScheduler_Worker-8] DEBUG kbplus.DataloadService  - updateES - com.k_int.kbplus.Platform
2017-06-06 10:20:00,223 [quartzScheduler_Worker-8] DEBUG kbplus.DataloadService  - result of findByDomain: com.k_int.kbplus.FTControl : 11
2017-06-06 10:20:00,223 [quartzScheduler_Worker-8] DEBUG kbplus.DataloadService  - updateES com.k_int.kbplus.Platform since 0
2017-06-06 10:20:00,224 [quartzScheduler_Worker-8] DEBUG kbplus.DataloadService  - Query completed.. processing rows...
2017-06-06 10:20:00,234 [quartzScheduler_Worker-8] ERROR kbplus.DataloadService  - Problem with FT index
org.elasticsearch.indices.TypeMissingException: [kbplus] type[[com.k_int.kbplus.Platform, trying to auto create mapping, but dynamic mapping is disabled]] missing
        at org.elasticsearch.index.mapper.MapperService.documentMapperWithAutoCreate(MapperService.java:474)
        at org.elasticsearch.index.shard.IndexShard.prepareIndex(IndexShard.java:491)
        at org.elasticsearch.action.index.TransportIndexAction.shardOperationOnPrimary(TransportIndexAction.java:192)
        at org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction$PrimaryPhase.performOnPrimary(TransportShardReplicationOperationAction.java:574)
        at org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction$PrimaryPhase$1.doRun(TransportShardReplicationOperationAction.java:440)
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:36)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
2017-06-06 10:20:00,234 [quartzScheduler_Worker-8] DEBUG kbplus.DataloadService  - Completed processing on com.k_int.kbplus.Platform - saved 0 records
2017-06-06 10:20:00,234 [quartzScheduler_Worker-8] DEBUG kbplus.DataloadService  - updateES - com.k_int.kbplus.Subscription
2017-06-06 10:20:00,236 [quartzScheduler_Worker-8] DEBUG kbplus.DataloadService  - result of findByDomain: com.k_int.kbplus.FTControl : 12
2017-06-06 10:20:00,236 [quartzScheduler_Worker-8] DEBUG kbplus.DataloadService  - updateES com.k_int.kbplus.Subscription since 1496409155000
2017-06-06 10:20:00,237 [quartzScheduler_Worker-8] DEBUG kbplus.DataloadService  - Query completed.. processing rows...
2017-06-06 10:20:00,237 [quartzScheduler_Worker-8] DEBUG kbplus.DataloadService  - Processed 0 records for com.k_int.kbplus.Subscription
2017-06-06 10:20:00,238 [quartzScheduler_Worker-8] DEBUG kbplus.DataloadService  - Completed processing on com.k_int.kbplus.Subscription - saved 0 records
2017-06-06 10:20:00,285 [quartzScheduler_Worker-8] DEBUG kbplus.DataloadService  - IndexUpdateJob completed in 166ms at Tue Jun 06 10:20:00 CEST 2017
2017-06-06 10:21:21,945 [http-nio-8080-exec-7] DEBUG kbplus.AdminController  - manageGlobalSources...
2017-06-06 10:21:51,374 [http-nio-8080-exec-3] DEBUG kbplus.AdminController  - start global sync...
2017-06-06 10:21:51,376 [http-nio-8080-exec-3] WARN  kbplus.GlobalSourceSyncService  - Not starting duplicate OAI thread
2017-06-06 10:21:51,378 [http-nio-8080-exec-3] DEBUG kbplus.AdminController  - done global sync...
2017-06-06 10:21:51,391 [http-nio-8080-exec-4] DEBUG kbplus.HomeController  - HomeController::index - 6
2017-06-06 10:21:51,421 [http-nio-8080-exec-2] DEBUG kbplus.MyInstitutionsController  - Count3=0

**Comment by Moetez16** [comment]
Sorry, sehe jetzt in den Logs, dass was passiert.

**Comment by Moetez16** [comment]
Momentan sehe ich das in den Logs für jedes Package:
![2017-06-06 11_03_11](https://cloud.githubusercontent.com/assets/20820400/26821771/e3c12b9a-4aa7-11e7-9c06-aed6243af8cb.png)


Es wird alles schön angelegt. Aber wenn ich in LASER auf Data Managers -> Global Data Download gehe, wird mir nichts angezeigt. Da sollte doch die ganzen Pakete die von der GOKB gezogen sind, sichtbar sein oder nicht ?

**Comment by Moetez16** [comment]
Nach dem heutigem Telefongespräch habe ich KBPlus lokal auf meinem Rechner laufen lassen und dann die Live GOKB als OAI Schnittstelle in KBPlus eingestellt. 

Result war, dass die OAI Schnittstelle ohne Probleme lief und Packages in KBPlus eingezeigt wurden. 

@hornmo : Kannst bitte local bei dir mal testen, ob es geht, wenn du als OAI Schnittstelle die HBZ Gokb angibst. Danke. 

@hornmo : Kannst du mir vlt eure GBV GOKB Daten mal zum testen per Email zuschicken. Danke.

**Comment by hornmo** [comment]
> Kannst bitte local bei dir mal testen, ob es geht, wenn du als OAI Schnittstelle die HBZ Gokb angibst.
> Danke.

Das ist eine gute Idee, ich berichte dann.

> Kannst du mir vlt eure GBV GOKB Daten mal zum testen per Email zuschicken. Danke.

Meinst du Titel- und Paketdaten als Datei oder eine URL zur Schnittstelle?
Unsere GOKb-Instanz liegt zur Zeit auf einer VM, die nur intern zugänglich ist. Ob wir die evtl. öffentlich machen sollten, müssten wir noch besprechen.

**Comment by hornmo** [comment]
Unten ist die Exception bei der Paketverarbeitung bei mir. Ich schaue mir das gerade an.

`2017-06-14 14:43:36,108 [pool-4-thread-1] DEBUG kbplus.TitleInstance  - looking for identifier isbn:978-3-658-04336-0
2017-06-14 14:43:36,117 [pool-4-thread-1] ERROR kbplus.GlobalSourceSyncService  - Problem
org.springframework.core.convert.ConverterNotFoundException: No converter found capable of converting from type java.util.LinkedHashMap<?, ?> to type com.k_int.kbplus.Identifier
	at org.grails.datastore.mapping.model.types.conversion.DefaultConversionService.convert(DefaultConversionService.java:43)
	at org.grails.datastore.gorm.GormStaticApi.methodMissing(GormStaticApi.groovy:105)
	at com.k_int.kbplus.TitleInstance$_lookupOrCreate_closure11.doCall(TitleInstance.groovy:314)
	at com.k_int.kbplus.TitleInstance.lookupOrCreate(TitleInstance.groovy:304)
	at com.k_int.kbplus.GlobalSourceSyncService.harmoniseTitleIdentifiers(GlobalSourceSyncService.groovy:790)
	at GrailsMelodyGrailsPlugin$_closure4$_closure16$_closure17.doCall(GrailsMelodyGrailsPlugin.groovy:184)
	at com.k_int.kbplus.GlobalSourceSyncService$_closure6$_closure44.doCall(GlobalSourceSyncService.groovy:484)
	at com.k_int.kbplus.GlobalSourceSyncService$_closure6.doCall(GlobalSourceSyncService.groovy:450)
	at com.k_int.kbplus.GlobalSourceSyncService$_intOAI_closure11.doCall(GlobalSourceSyncService.groovy:663)
	at com.k_int.goai.OaiClient$_getChangesSince_closure1_closure2_closure4.doCall(OaiClient.groovy:47)
	at com.k_int.goai.OaiClient$_getChangesSince_closure1_closure2.doCall(OaiClient.groovy:43)
	at groovyx.net.http.HTTPBuilder.doRequest(HTTPBuilder.java:508)
	at groovyx.net.http.HTTPBuilder.doRequest(HTTPBuilder.java:441)
	at groovyx.net.http.HTTPBuilder.request(HTTPBuilder.java:390)
	at com.k_int.goai.OaiClient.getChangesSince(OaiClient.groovy:28)
	at com.k_int.kbplus.GlobalSourceSyncService.intOAI(GlobalSourceSyncService.groovy:625)
	at com.k_int.kbplus.GlobalSourceSyncService.doOAISync(GlobalSourceSyncService.groovy:590)
	at GrailsMelodyGrailsPlugin$_closure4$_closure16$_closure17.doCall(GrailsMelodyGrailsPlugin.groovy:184)
	at com.k_int.kbplus.GlobalSourceSyncService$_internalRunAllActiveSyncTasks_closure9.doCall(GlobalSourceSyncService.groovy:573)
	at com.k_int.kbplus.GlobalSourceSyncService.internalRunAllActiveSyncTasks(GlobalSourceSyncService.groovy:559)
	at GrailsMelodyGrailsPlugin$_closure4$_closure16$_closure17.doCall(GrailsMelodyGrailsPlugin.groovy:184)
	at com.k_int.kbplus.GlobalSourceSyncService$_runAllActiveSyncTasks_closure8.doCall(GlobalSourceSyncService.groovy:546)
	at grails.plugin.executor.PersistenceContextRunnableWrapper$_run_closure1.doCall(PersistenceContextRunnableWrapper.groovy:34)
	at grails.plugin.executor.PersistenceContextWrapper.wrap(PersistenceContextWrapper.groovy:35)
	at grails.plugin.executor.PersistenceContextRunnableWrapper.run(PersistenceContextRunnableWrapper.groovy:34)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
2017-06-14 14:43:36,120 [pool-4-thread-1] ERROR kbplus.GlobalSourceSyncService  - Problem running job 5, conf=[name:Package, converter:com.k_int.kbplus.GlobalSourceSyncService$_closure6@eb12afc, reconciler:com.k_int.kbplus.GlobalSourceSyncService$_closure3@117d0ded, newRemoteRecordHandler:null, complianceCheck:com.k_int.kbplus.GlobalSourceSyncService$_closure5@291d4b93]
org.springframework.core.convert.ConverterNotFoundException: No converter found capable of converting from type java.util.LinkedHashMap<?, ?> to type com.k_int.kbplus.Identifier
	at org.grails.datastore.mapping.model.types.conversion.DefaultConversionService.convert(DefaultConversionService.java:43)
	at org.grails.datastore.gorm.GormStaticApi.methodMissing(GormStaticApi.groovy:105)
	at com.k_int.kbplus.TitleInstance$_lookupOrCreate_closure11.doCall(TitleInstance.groovy:314)
	at com.k_int.kbplus.TitleInstance.lookupOrCreate(TitleInstance.groovy:304)
	at com.k_int.kbplus.GlobalSourceSyncService.harmoniseTitleIdentifiers(GlobalSourceSyncService.groovy:790)
	at GrailsMelodyGrailsPlugin$_closure4$_closure16$_closure17.doCall(GrailsMelodyGrailsPlugin.groovy:184)
	at com.k_int.kbplus.GlobalSourceSyncService$_closure6$_closure44.doCall(GlobalSourceSyncService.groovy:484)
	at com.k_int.kbplus.GlobalSourceSyncService$_closure6.doCall(GlobalSourceSyncService.groovy:450)
	at com.k_int.kbplus.GlobalSourceSyncService$_intOAI_closure11.doCall(GlobalSourceSyncService.groovy:663)
	at com.k_int.goai.OaiClient$_getChangesSince_closure1_closure2_closure4.doCall(OaiClient.groovy:47)
	at com.k_int.goai.OaiClient$_getChangesSince_closure1_closure2.doCall(OaiClient.groovy:43)
	at groovyx.net.http.HTTPBuilder.doRequest(HTTPBuilder.java:508)
	at groovyx.net.http.HTTPBuilder.doRequest(HTTPBuilder.java:441)
	at groovyx.net.http.HTTPBuilder.request(HTTPBuilder.java:390)
	at com.k_int.goai.OaiClient.getChangesSince(OaiClient.groovy:28)
	at com.k_int.kbplus.GlobalSourceSyncService.intOAI(GlobalSourceSyncService.groovy:625)
	at com.k_int.kbplus.GlobalSourceSyncService.doOAISync(GlobalSourceSyncService.groovy:590)
	at GrailsMelodyGrailsPlugin$_closure4$_closure16$_closure17.doCall(GrailsMelodyGrailsPlugin.groovy:184)
	at com.k_int.kbplus.GlobalSourceSyncService$_internalRunAllActiveSyncTasks_closure9.doCall(GlobalSourceSyncService.groovy:573)
	at com.k_int.kbplus.GlobalSourceSyncService.internalRunAllActiveSyncTasks(GlobalSourceSyncService.groovy:559)
	at GrailsMelodyGrailsPlugin$_closure4$_closure16$_closure17.doCall(GrailsMelodyGrailsPlugin.groovy:184)
	at com.k_int.kbplus.GlobalSourceSyncService$_runAllActiveSyncTasks_closure8.doCall(GlobalSourceSyncService.groovy:546)
	at grails.plugin.executor.PersistenceContextRunnableWrapper$_run_closure1.doCall(PersistenceContextRunnableWrapper.groovy:34)
	at grails.plugin.executor.PersistenceContextWrapper.wrap(PersistenceContextWrapper.groovy:35)
	at grails.plugin.executor.PersistenceContextRunnableWrapper.run(PersistenceContextRunnableWrapper.groovy:34)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)`

**Comment by hornmo** [comment]
Bei mir funktioniert es jetzt, nachdem ich der KBPlus mehr RAM gegeben habe. Das Problem besteht darin, dass Pakete in der OAI-Antwort unter keinen Umständen aufgesplittet werden. Bei großen Paketen (wie bei denen auf der ersten Ergebnisseite im Phaeton) dauert die Übertragung der Daten dann einfach ewig lange, außerdem hatte ich in der KBPlus dann irgendwann Speicherprobleme. Als Verbesserung in der GOKb könnte man sich deshalb mal Gedanken machen, ob man die OAI-Records von Paketen irgendwie unterteilen kann. Da es aber theoretisch an der KBPlus liegt, sollte das Ticket auch dorthin wandern, und hier eindeutig nicht als Bug der GOKb markiert werden.

**Comment by Moetez16** [comment]
Ok. Danke für den Hinweis. Ich werde den RAM erhöhen und dann es mal testen. 

Mit wieviel RAM hast du es getestet?

Danke.

**Comment by hornmo** [comment]
Bei mir war Java bei ca. 1.8GB. Mit 2GB funktioniert es. Die Antwort bei der ersten Anfrage hat ein paar Minuten gedauert, aber dann ging es los.

... Aber man sieht, dass das schon problematisch ist. Stellt man sich ein E-Book-Paket mit 100.000 Titeln vor, dann sehe ich da schwarz.

**Comment by Moetez16** [comment]
Bei uns ist Java auf 8GB gesetzt.

**Comment by hornmo** [comment]
Auch die Grails-Variablen?

**Comment by Moetez16** [comment]
So sieht es aus: 

export JAVA_OPTS="-Xmx10G -Xms1G  -server -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC"

export CATALINA_OPTS="-DJENKINS_HOME=/.jenkins/ -Xmx4G"

export GRAILS_OPTS="-XX:MaxPermSize=2G -Xmx4G -server -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC

**Comment by hornmo** [comment]
Relevant in GRAILS_HOME/bin/startGrails

`  if [ -n "$GRAILS_OPTS" ]
     then
        GRAILS_OPTS="$GRAILS_OPTS"
     else
        GRAILS_OPTS="-server -Xmx768M -Xms64M -Dfile.encoding=UTF-8"
        if [ "$GRAILS_NO_PERMGEN" != "1" ]; then
           GRAILS_OPTS="$GRAILS_OPTS -XX:PermSize=32m -XX:MaxPermSize=256m"
        fi
  fi
`

**Comment by hornmo** [comment]
hmm

**Comment by Moetez16** [comment]
http://laser-dev.hbz-nrw.de/sysAdmin/logViewer

Schau mal rein.

**Comment by Moetez16** [comment]
Hi, der Golab Data Sync ist durchgelaufen. Jedoch immer noch keine Daten in der KBPlus.

**Comment by hornmo** [comment]
Hmm, ich weiß nicht genau, was da das Problem sein könnte. Ich habe meine Änderungen für laser im Branch datasync-localisation committet. Vielleicht ist da die Lösung drin, obwohl ich nicht weiß, was das sein könnte.

**Comment by philboeselager** [comment]
Habe mir das Problem ausgehend von Laser "Start Global Data Sync" noch einmal angesehen. Aktuell erscheint ein zuvor ungesehener hql-Parsing-Fehler, dessen Ursache ich bisher nicht finden kann. catalina.out loggt (siehe auch  [catalina.out.20170904_1720.txt](https://github.com/hbz/gokb-phase1/files/1278037/catalina.out.20170904_1720.txt) ) : 

    2017-09-04 17:20:16,952 [http-nio-8080-exec-35] ERROR hql.PARSER  - line 1:50: unexpected token: and
    2017-09-04 17:20:17,115 [http-nio-8080-exec-35] ERROR errors.GrailsExceptionResolver  - QuerySyntaxException occurred when processing request: [GET] /gokb/oai/packages
    unexpected token: and near line 1, column 50 [select count(o)  from org.gokb.cred.Package as o and o.lastUpdated > ?].

Mehr Details finden sich in [stacktrace.log.20170904_1720.txt](https://github.com/hbz/gokb-phase1/files/1278038/stacktrace.log.20170904_1720.txt) .

Bislang ist unklar, warum der Fehler überhaupt neuerdings entsteht, sagt doch die [Historie](https://github.com/hbz/gokb-phase1/blame/v7_dev_integration/server/gokb/grails-app/controllers/org/gokb/OaiController.groovy), dass im Controller zuletzt gar nichts Entsprechendes geändert wurde.

Auch im entsprechenden laser-Aufruf wurde seit Juli nichts Entscheidendes geändert, siehe [hier](https://github.com/hbz/laser/commit/12141f6f2799d0b17ddfcee80a7ad2ec19e99b51#diff-4d3dadbb86460fcf66dc2807bad908d8L202).

@hornmo : fällt Dir noch ein Ansatz für die Fehlerursachen-Eingrenzung ein?

**Comment by hornmo** [comment]
@philboeselager : Ich habe mir das angeschaut und es war ein Problem in den Domainklassen von Package und TitleInstance, aus denen Teile der HQL-Requests genommen werden. Hatte ich letztens anscheinend kaputt gemacht. Ich öffne gleich noch einen neuen Pull-Request. Dieser Fehler hat jedoch nichts mit dem ursprünglichen zu tun, der ziehmlich sicher bei der KB+ liegt.

**Comment by philboeselager** [comment]
@hornmo : Super, habe gemerged. Eine Verständnisfrage: Wodurch wurde die Aufteilung von query und statusFilter erforderlich, bzw. wieso war sie vorher nicht vorhanden?

**Comment by hornmo** [comment]
@philboeselager Der OaiController hat für die jeweiligen Anfragen die Bezeichnungen aus der jeweiligen Domainklasse genommen. So wie das vorher formuliert war, musste in diesem String die erste WHERE-Kondition drinstehen (z.B. "where o.status.value = 'Deleted'") und alle im OaiController hinzugefügten Filter wurden dementsprechend mit 'AND' eingeleitet. Damit gab es keine Möglichkeit, die Einschränkung nach Status wegzulassen. Das könnte aber unter Umständen gewollt sein. Vielleicht will man für einzelne Endpunkte auch gelöschte Objekte übertragen, damit man in den konsumierenden Systemen nicht raten muss, was mit Datensätzen passiert ist, die irgendwann mal mitkamen, aber auf einmal nicht mehr in den Antworten übertragen werden. Die neue Erweiterung macht das ganze etwas flexibler.

**Comment by hornmo** [comment]
@philboeselager Alternativ hätte man sicher auch im OaiController einfach den queryString nach dem "where" durchsuchen können, aber so ist es denke ich etwas klarer strukturiert. Man könnte auch darüber nachdenken, das unter Umständen noch weiter zu treiben, so dass man gar nicht mehr mit irgendwelchen Strings rumhantieren muss...

**Comment by philboeselager** [comment]
@hornmo : ich deploye die Änderungen heute oder morgen und gebe Dir dann noch einmal Bescheid.

**Comment by philboeselager** [comment]
@hornmo : Die Änderungen sind deployt. Die Exception wird durch den laser Global Data Sync nicht mehr erzeugt.

**Comment by philboeselager** [comment]
@Moetez16 Aus meiner Sicht kann dieses Ticket dann geschlossen werden - oder wollen wir es für die noch notwendigen Änderungen in laser (Global Data Sync) weiter benutzen?

**Comment by philboeselager** [comment]
Mangels Aktivität und aufgrund der nicht mehr gegebenen Relevanz für die GOKb schließe ich dieses Ticket. Ggf. kann es natürlich von LAS:eR aus verlinkt werden.
